#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice.h>
#include <cydevice_trm.h>

/* Counter_CounterUDB */
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_A0_REG CYREG_B1_UDB10_11_A0
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_A1_REG CYREG_B1_UDB10_11_A1
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_D0_REG CYREG_B1_UDB10_11_D0
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_D1_REG CYREG_B1_UDB10_11_D1
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_DP_AUX_CTL_REG CYREG_B1_UDB10_11_ACTL
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_F0_REG CYREG_B1_UDB10_11_F0
#define Counter_CounterUDB_sC16_counterdp_u0__16BIT_F1_REG CYREG_B1_UDB10_11_F1
#define Counter_CounterUDB_sC16_counterdp_u0__A0_A1_REG CYREG_B1_UDB10_A0_A1
#define Counter_CounterUDB_sC16_counterdp_u0__A0_REG CYREG_B1_UDB10_A0
#define Counter_CounterUDB_sC16_counterdp_u0__A1_REG CYREG_B1_UDB10_A1
#define Counter_CounterUDB_sC16_counterdp_u0__D0_D1_REG CYREG_B1_UDB10_D0_D1
#define Counter_CounterUDB_sC16_counterdp_u0__D0_REG CYREG_B1_UDB10_D0
#define Counter_CounterUDB_sC16_counterdp_u0__D1_REG CYREG_B1_UDB10_D1
#define Counter_CounterUDB_sC16_counterdp_u0__DP_AUX_CTL_REG CYREG_B1_UDB10_ACTL
#define Counter_CounterUDB_sC16_counterdp_u0__F0_F1_REG CYREG_B1_UDB10_F0_F1
#define Counter_CounterUDB_sC16_counterdp_u0__F0_REG CYREG_B1_UDB10_F0
#define Counter_CounterUDB_sC16_counterdp_u0__F1_REG CYREG_B1_UDB10_F1
#define Counter_CounterUDB_sC16_counterdp_u0__MSK_DP_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define Counter_CounterUDB_sC16_counterdp_u0__PER_DP_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define Counter_CounterUDB_sC16_counterdp_u1__A0_A1_REG CYREG_B1_UDB11_A0_A1
#define Counter_CounterUDB_sC16_counterdp_u1__A0_REG CYREG_B1_UDB11_A0
#define Counter_CounterUDB_sC16_counterdp_u1__A1_REG CYREG_B1_UDB11_A1
#define Counter_CounterUDB_sC16_counterdp_u1__D0_D1_REG CYREG_B1_UDB11_D0_D1
#define Counter_CounterUDB_sC16_counterdp_u1__D0_REG CYREG_B1_UDB11_D0
#define Counter_CounterUDB_sC16_counterdp_u1__D1_REG CYREG_B1_UDB11_D1
#define Counter_CounterUDB_sC16_counterdp_u1__DP_AUX_CTL_REG CYREG_B1_UDB11_ACTL
#define Counter_CounterUDB_sC16_counterdp_u1__F0_F1_REG CYREG_B1_UDB11_F0_F1
#define Counter_CounterUDB_sC16_counterdp_u1__F0_REG CYREG_B1_UDB11_F0
#define Counter_CounterUDB_sC16_counterdp_u1__F1_REG CYREG_B1_UDB11_F1
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB10_11_ACTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB10_11_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB10_11_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB10_11_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_B1_UDB10_11_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_MASK_REG CYREG_B1_UDB10_11_MSK
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_B1_UDB10_11_MSK
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_B1_UDB10_11_MSK
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB10_11_MSK
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__7__MASK 0x80u
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__7__POS 7
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_AUX_CTL_REG CYREG_B1_UDB10_ACTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG CYREG_B1_UDB10_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_ST_REG CYREG_B1_UDB10_ST_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_REG CYREG_B1_UDB10_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_ST_REG CYREG_B1_UDB10_ST_CTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__MASK 0x80u
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__PERIOD_REG CYREG_B1_UDB10_MSK
#define Counter_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_B1_UDB10_MSK_ACTL
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__0__MASK 0x01u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__0__POS 0
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__1__MASK 0x02u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__1__POS 1
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__2__MASK 0x04u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__2__POS 2
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__4__MASK 0x10u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__4__POS 4
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__5__MASK 0x20u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__5__POS 5
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__6__MASK 0x40u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__6__POS 6
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__MASK 0x77u
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__MASK_REG CYREG_B1_UDB11_MSK
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_B1_UDB11_ACTL
#define Counter_CounterUDB_sSTSReg_rstSts_stsreg__STATUS_REG CYREG_B1_UDB11_ST

/* ADC_Ext_CP_Clk */
#define ADC_Ext_CP_Clk__CFG0 CYREG_CLKDIST_DCFG0_CFG0
#define ADC_Ext_CP_Clk__CFG1 CYREG_CLKDIST_DCFG0_CFG1
#define ADC_Ext_CP_Clk__CFG2 CYREG_CLKDIST_DCFG0_CFG2
#define ADC_Ext_CP_Clk__CFG2_SRC_SEL_MASK 0x07u
#define ADC_Ext_CP_Clk__INDEX 0x00u
#define ADC_Ext_CP_Clk__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_Ext_CP_Clk__PM_ACT_MSK 0x01u
#define ADC_Ext_CP_Clk__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_Ext_CP_Clk__PM_STBY_MSK 0x01u

/* Timer_TimerUDB */
#define Timer_TimerUDB_rstSts_stsreg__0__MASK 0x01u
#define Timer_TimerUDB_rstSts_stsreg__0__POS 0
#define Timer_TimerUDB_rstSts_stsreg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB10_11_ACTL
#define Timer_TimerUDB_rstSts_stsreg__16BIT_STATUS_REG CYREG_B0_UDB10_11_ST
#define Timer_TimerUDB_rstSts_stsreg__2__MASK 0x04u
#define Timer_TimerUDB_rstSts_stsreg__2__POS 2
#define Timer_TimerUDB_rstSts_stsreg__3__MASK 0x08u
#define Timer_TimerUDB_rstSts_stsreg__3__POS 3
#define Timer_TimerUDB_rstSts_stsreg__MASK 0x0Du
#define Timer_TimerUDB_rstSts_stsreg__MASK_REG CYREG_B0_UDB10_MSK
#define Timer_TimerUDB_rstSts_stsreg__MASK_ST_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Timer_TimerUDB_rstSts_stsreg__PER_ST_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Timer_TimerUDB_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_B0_UDB10_ACTL
#define Timer_TimerUDB_rstSts_stsreg__STATUS_CNT_REG CYREG_B0_UDB10_ST_CTL
#define Timer_TimerUDB_rstSts_stsreg__STATUS_CONTROL_REG CYREG_B0_UDB10_ST_CTL
#define Timer_TimerUDB_rstSts_stsreg__STATUS_REG CYREG_B0_UDB10_ST
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB11_12_ACTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB11_12_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB11_12_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB11_12_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB11_12_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_MASK_REG CYREG_B0_UDB11_12_MSK
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB11_12_MSK
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB11_12_MSK
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB11_12_MSK
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__7__MASK 0x80u
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__7__POS 7
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_AUX_CTL_REG CYREG_B0_UDB11_ACTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG CYREG_B0_UDB11_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_ST_REG CYREG_B0_UDB11_ST_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_REG CYREG_B0_UDB11_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_ST_REG CYREG_B0_UDB11_ST_CTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__MASK 0x80u
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__PERIOD_REG CYREG_B0_UDB11_MSK
#define Timer_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_A0_REG CYREG_B0_UDB08_09_A0
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_A1_REG CYREG_B0_UDB08_09_A1
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_D0_REG CYREG_B0_UDB08_09_D0
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_D1_REG CYREG_B0_UDB08_09_D1
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB08_09_ACTL
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_F0_REG CYREG_B0_UDB08_09_F0
#define Timer_TimerUDB_sT24_timerdp_u0__16BIT_F1_REG CYREG_B0_UDB08_09_F1
#define Timer_TimerUDB_sT24_timerdp_u0__A0_A1_REG CYREG_B0_UDB08_A0_A1
#define Timer_TimerUDB_sT24_timerdp_u0__A0_REG CYREG_B0_UDB08_A0
#define Timer_TimerUDB_sT24_timerdp_u0__A1_REG CYREG_B0_UDB08_A1
#define Timer_TimerUDB_sT24_timerdp_u0__D0_D1_REG CYREG_B0_UDB08_D0_D1
#define Timer_TimerUDB_sT24_timerdp_u0__D0_REG CYREG_B0_UDB08_D0
#define Timer_TimerUDB_sT24_timerdp_u0__D1_REG CYREG_B0_UDB08_D1
#define Timer_TimerUDB_sT24_timerdp_u0__DP_AUX_CTL_REG CYREG_B0_UDB08_ACTL
#define Timer_TimerUDB_sT24_timerdp_u0__F0_F1_REG CYREG_B0_UDB08_F0_F1
#define Timer_TimerUDB_sT24_timerdp_u0__F0_REG CYREG_B0_UDB08_F0
#define Timer_TimerUDB_sT24_timerdp_u0__F1_REG CYREG_B0_UDB08_F1
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_A0_REG CYREG_B0_UDB09_10_A0
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_A1_REG CYREG_B0_UDB09_10_A1
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_D0_REG CYREG_B0_UDB09_10_D0
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_D1_REG CYREG_B0_UDB09_10_D1
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB09_10_ACTL
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_F0_REG CYREG_B0_UDB09_10_F0
#define Timer_TimerUDB_sT24_timerdp_u1__16BIT_F1_REG CYREG_B0_UDB09_10_F1
#define Timer_TimerUDB_sT24_timerdp_u1__A0_A1_REG CYREG_B0_UDB09_A0_A1
#define Timer_TimerUDB_sT24_timerdp_u1__A0_REG CYREG_B0_UDB09_A0
#define Timer_TimerUDB_sT24_timerdp_u1__A1_REG CYREG_B0_UDB09_A1
#define Timer_TimerUDB_sT24_timerdp_u1__D0_D1_REG CYREG_B0_UDB09_D0_D1
#define Timer_TimerUDB_sT24_timerdp_u1__D0_REG CYREG_B0_UDB09_D0
#define Timer_TimerUDB_sT24_timerdp_u1__D1_REG CYREG_B0_UDB09_D1
#define Timer_TimerUDB_sT24_timerdp_u1__DP_AUX_CTL_REG CYREG_B0_UDB09_ACTL
#define Timer_TimerUDB_sT24_timerdp_u1__F0_F1_REG CYREG_B0_UDB09_F0_F1
#define Timer_TimerUDB_sT24_timerdp_u1__F0_REG CYREG_B0_UDB09_F0
#define Timer_TimerUDB_sT24_timerdp_u1__F1_REG CYREG_B0_UDB09_F1
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_A0_REG CYREG_B0_UDB10_11_A0
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_A1_REG CYREG_B0_UDB10_11_A1
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_D0_REG CYREG_B0_UDB10_11_D0
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_D1_REG CYREG_B0_UDB10_11_D1
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB10_11_ACTL
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_F0_REG CYREG_B0_UDB10_11_F0
#define Timer_TimerUDB_sT24_timerdp_u2__16BIT_F1_REG CYREG_B0_UDB10_11_F1
#define Timer_TimerUDB_sT24_timerdp_u2__A0_A1_REG CYREG_B0_UDB10_A0_A1
#define Timer_TimerUDB_sT24_timerdp_u2__A0_REG CYREG_B0_UDB10_A0
#define Timer_TimerUDB_sT24_timerdp_u2__A1_REG CYREG_B0_UDB10_A1
#define Timer_TimerUDB_sT24_timerdp_u2__D0_D1_REG CYREG_B0_UDB10_D0_D1
#define Timer_TimerUDB_sT24_timerdp_u2__D0_REG CYREG_B0_UDB10_D0
#define Timer_TimerUDB_sT24_timerdp_u2__D1_REG CYREG_B0_UDB10_D1
#define Timer_TimerUDB_sT24_timerdp_u2__DP_AUX_CTL_REG CYREG_B0_UDB10_ACTL
#define Timer_TimerUDB_sT24_timerdp_u2__F0_F1_REG CYREG_B0_UDB10_F0_F1
#define Timer_TimerUDB_sT24_timerdp_u2__F0_REG CYREG_B0_UDB10_F0
#define Timer_TimerUDB_sT24_timerdp_u2__F1_REG CYREG_B0_UDB10_F1
#define Timer_TimerUDB_sT24_timerdp_u2__MSK_DP_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Timer_TimerUDB_sT24_timerdp_u2__PER_DP_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL

/* Accelerator */
#define Accelerator__0__MASK 0x20u
#define Accelerator__0__PC CYREG_PRT6_PC5
#define Accelerator__0__PORT 6u
#define Accelerator__0__SHIFT 5
#define Accelerator__AG CYREG_PRT6_AG
#define Accelerator__AMUX CYREG_PRT6_AMUX
#define Accelerator__BIE CYREG_PRT6_BIE
#define Accelerator__BIT_MASK CYREG_PRT6_BIT_MASK
#define Accelerator__BYP CYREG_PRT6_BYP
#define Accelerator__CTL CYREG_PRT6_CTL
#define Accelerator__DM0 CYREG_PRT6_DM0
#define Accelerator__DM1 CYREG_PRT6_DM1
#define Accelerator__DM2 CYREG_PRT6_DM2
#define Accelerator__DR CYREG_PRT6_DR
#define Accelerator__INP_DIS CYREG_PRT6_INP_DIS
#define Accelerator__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Accelerator__LCD_EN CYREG_PRT6_LCD_EN
#define Accelerator__MASK 0x20u
#define Accelerator__PORT 6u
#define Accelerator__PRT CYREG_PRT6_PRT
#define Accelerator__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Accelerator__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Accelerator__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Accelerator__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Accelerator__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Accelerator__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Accelerator__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Accelerator__PS CYREG_PRT6_PS
#define Accelerator__SHIFT 5
#define Accelerator__SLW CYREG_PRT6_SLW

/* ADC_theACLK */
#define ADC_theACLK__CFG0 CYREG_CLKDIST_ACFG0_CFG0
#define ADC_theACLK__CFG1 CYREG_CLKDIST_ACFG0_CFG1
#define ADC_theACLK__CFG2 CYREG_CLKDIST_ACFG0_CFG2
#define ADC_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define ADC_theACLK__CFG3 CYREG_CLKDIST_ACFG0_CFG3
#define ADC_theACLK__CFG3_PHASE_DLY_MASK 0x0Fu
#define ADC_theACLK__INDEX 0x00u
#define ADC_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG1
#define ADC_theACLK__PM_ACT_MSK 0x01u
#define ADC_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG1
#define ADC_theACLK__PM_STBY_MSK 0x01u

/* LCD_LCDPort */
#define LCD_LCDPort__0__MASK 0x01u
#define LCD_LCDPort__0__PC CYREG_PRT2_PC0
#define LCD_LCDPort__0__PORT 2u
#define LCD_LCDPort__0__SHIFT 0
#define LCD_LCDPort__1__MASK 0x02u
#define LCD_LCDPort__1__PC CYREG_PRT2_PC1
#define LCD_LCDPort__1__PORT 2u
#define LCD_LCDPort__1__SHIFT 1
#define LCD_LCDPort__2__MASK 0x04u
#define LCD_LCDPort__2__PC CYREG_PRT2_PC2
#define LCD_LCDPort__2__PORT 2u
#define LCD_LCDPort__2__SHIFT 2
#define LCD_LCDPort__3__MASK 0x08u
#define LCD_LCDPort__3__PC CYREG_PRT2_PC3
#define LCD_LCDPort__3__PORT 2u
#define LCD_LCDPort__3__SHIFT 3
#define LCD_LCDPort__4__MASK 0x10u
#define LCD_LCDPort__4__PC CYREG_PRT2_PC4
#define LCD_LCDPort__4__PORT 2u
#define LCD_LCDPort__4__SHIFT 4
#define LCD_LCDPort__5__MASK 0x20u
#define LCD_LCDPort__5__PC CYREG_PRT2_PC5
#define LCD_LCDPort__5__PORT 2u
#define LCD_LCDPort__5__SHIFT 5
#define LCD_LCDPort__6__MASK 0x40u
#define LCD_LCDPort__6__PC CYREG_PRT2_PC6
#define LCD_LCDPort__6__PORT 2u
#define LCD_LCDPort__6__SHIFT 6
#define LCD_LCDPort__AG CYREG_PRT2_AG
#define LCD_LCDPort__AMUX CYREG_PRT2_AMUX
#define LCD_LCDPort__BIE CYREG_PRT2_BIE
#define LCD_LCDPort__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_LCDPort__BYP CYREG_PRT2_BYP
#define LCD_LCDPort__CTL CYREG_PRT2_CTL
#define LCD_LCDPort__DM0 CYREG_PRT2_DM0
#define LCD_LCDPort__DM1 CYREG_PRT2_DM1
#define LCD_LCDPort__DM2 CYREG_PRT2_DM2
#define LCD_LCDPort__DR CYREG_PRT2_DR
#define LCD_LCDPort__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_LCDPort__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_LCDPort__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_LCDPort__MASK 0x7Fu
#define LCD_LCDPort__PORT 2u
#define LCD_LCDPort__PRT CYREG_PRT2_PRT
#define LCD_LCDPort__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_LCDPort__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_LCDPort__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_LCDPort__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_LCDPort__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_LCDPort__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_LCDPort__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_LCDPort__PS CYREG_PRT2_PS
#define LCD_LCDPort__SHIFT 0
#define LCD_LCDPort__SLW CYREG_PRT2_SLW

/* PWM_PWMUDB */
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB10_11_ACTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB10_11_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB10_11_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB10_11_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB10_11_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_MASK_REG CYREG_B0_UDB10_11_MSK
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB10_11_MSK
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB10_11_MSK
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB10_11_MSK
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__7__MASK 0x80u
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__7__POS 7
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_AUX_CTL_REG CYREG_B0_UDB10_ACTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG CYREG_B0_UDB10_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_ST_REG CYREG_B0_UDB10_ST_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_REG CYREG_B0_UDB10_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_ST_REG CYREG_B0_UDB10_ST_CTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__MASK 0x80u
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__PERIOD_REG CYREG_B0_UDB10_MSK
#define PWM_PWMUDB_sCTRLReg_SyncCtl_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_A0_REG CYREG_B0_UDB12_13_A0
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_A1_REG CYREG_B0_UDB12_13_A1
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_D0_REG CYREG_B0_UDB12_13_D0
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_D1_REG CYREG_B0_UDB12_13_D1
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB12_13_ACTL
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_F0_REG CYREG_B0_UDB12_13_F0
#define PWM_PWMUDB_sP16_pwmdp_u0__16BIT_F1_REG CYREG_B0_UDB12_13_F1
#define PWM_PWMUDB_sP16_pwmdp_u0__A0_A1_REG CYREG_B0_UDB12_A0_A1
#define PWM_PWMUDB_sP16_pwmdp_u0__A0_REG CYREG_B0_UDB12_A0
#define PWM_PWMUDB_sP16_pwmdp_u0__A1_REG CYREG_B0_UDB12_A1
#define PWM_PWMUDB_sP16_pwmdp_u0__D0_D1_REG CYREG_B0_UDB12_D0_D1
#define PWM_PWMUDB_sP16_pwmdp_u0__D0_REG CYREG_B0_UDB12_D0
#define PWM_PWMUDB_sP16_pwmdp_u0__D1_REG CYREG_B0_UDB12_D1
#define PWM_PWMUDB_sP16_pwmdp_u0__DP_AUX_CTL_REG CYREG_B0_UDB12_ACTL
#define PWM_PWMUDB_sP16_pwmdp_u0__F0_F1_REG CYREG_B0_UDB12_F0_F1
#define PWM_PWMUDB_sP16_pwmdp_u0__F0_REG CYREG_B0_UDB12_F0
#define PWM_PWMUDB_sP16_pwmdp_u0__F1_REG CYREG_B0_UDB12_F1
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_A0_REG CYREG_B0_UDB13_14_A0
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_A1_REG CYREG_B0_UDB13_14_A1
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_D0_REG CYREG_B0_UDB13_14_D0
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_D1_REG CYREG_B0_UDB13_14_D1
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_DP_AUX_CTL_REG CYREG_B0_UDB13_14_ACTL
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_F0_REG CYREG_B0_UDB13_14_F0
#define PWM_PWMUDB_sP16_pwmdp_u1__16BIT_F1_REG CYREG_B0_UDB13_14_F1
#define PWM_PWMUDB_sP16_pwmdp_u1__A0_A1_REG CYREG_B0_UDB13_A0_A1
#define PWM_PWMUDB_sP16_pwmdp_u1__A0_REG CYREG_B0_UDB13_A0
#define PWM_PWMUDB_sP16_pwmdp_u1__A1_REG CYREG_B0_UDB13_A1
#define PWM_PWMUDB_sP16_pwmdp_u1__D0_D1_REG CYREG_B0_UDB13_D0_D1
#define PWM_PWMUDB_sP16_pwmdp_u1__D0_REG CYREG_B0_UDB13_D0
#define PWM_PWMUDB_sP16_pwmdp_u1__D1_REG CYREG_B0_UDB13_D1
#define PWM_PWMUDB_sP16_pwmdp_u1__DP_AUX_CTL_REG CYREG_B0_UDB13_ACTL
#define PWM_PWMUDB_sP16_pwmdp_u1__F0_F1_REG CYREG_B0_UDB13_F0_F1
#define PWM_PWMUDB_sP16_pwmdp_u1__F0_REG CYREG_B0_UDB13_F0
#define PWM_PWMUDB_sP16_pwmdp_u1__F1_REG CYREG_B0_UDB13_F1
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__0__MASK 0x01u
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__0__POS 0
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB13_14_ACTL
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__16BIT_STATUS_REG CYREG_B0_UDB13_14_ST
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__2__MASK 0x04u
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__2__POS 2
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__3__MASK 0x08u
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__3__POS 3
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__5__MASK 0x20u
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__5__POS 5
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__MASK 0x2Du
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__MASK_REG CYREG_B0_UDB13_MSK
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_B0_UDB13_ACTL
#define PWM_PWMUDB_sSTSReg_rstSts_stsreg__STATUS_REG CYREG_B0_UDB13_ST

/* Tachometer */
#define Tachometer__0__MASK 0x80u
#define Tachometer__0__PC CYREG_PRT1_PC7
#define Tachometer__0__PORT 1u
#define Tachometer__0__SHIFT 7
#define Tachometer__AG CYREG_PRT1_AG
#define Tachometer__AMUX CYREG_PRT1_AMUX
#define Tachometer__BIE CYREG_PRT1_BIE
#define Tachometer__BIT_MASK CYREG_PRT1_BIT_MASK
#define Tachometer__BYP CYREG_PRT1_BYP
#define Tachometer__CTL CYREG_PRT1_CTL
#define Tachometer__DM0 CYREG_PRT1_DM0
#define Tachometer__DM1 CYREG_PRT1_DM1
#define Tachometer__DM2 CYREG_PRT1_DM2
#define Tachometer__DR CYREG_PRT1_DR
#define Tachometer__INP_DIS CYREG_PRT1_INP_DIS
#define Tachometer__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Tachometer__LCD_EN CYREG_PRT1_LCD_EN
#define Tachometer__MASK 0x80u
#define Tachometer__PORT 1u
#define Tachometer__PRT CYREG_PRT1_PRT
#define Tachometer__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Tachometer__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Tachometer__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Tachometer__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Tachometer__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Tachometer__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Tachometer__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Tachometer__PS CYREG_PRT1_PS
#define Tachometer__SHIFT 7
#define Tachometer__SLW CYREG_PRT1_SLW

/* Indicator */
#define Indicator__0__MASK 0x08u
#define Indicator__0__PC CYREG_PRT6_PC3
#define Indicator__0__PORT 6u
#define Indicator__0__SHIFT 3
#define Indicator__AG CYREG_PRT6_AG
#define Indicator__AMUX CYREG_PRT6_AMUX
#define Indicator__BIE CYREG_PRT6_BIE
#define Indicator__BIT_MASK CYREG_PRT6_BIT_MASK
#define Indicator__BYP CYREG_PRT6_BYP
#define Indicator__CTL CYREG_PRT6_CTL
#define Indicator__DM0 CYREG_PRT6_DM0
#define Indicator__DM1 CYREG_PRT6_DM1
#define Indicator__DM2 CYREG_PRT6_DM2
#define Indicator__DR CYREG_PRT6_DR
#define Indicator__INP_DIS CYREG_PRT6_INP_DIS
#define Indicator__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Indicator__LCD_EN CYREG_PRT6_LCD_EN
#define Indicator__MASK 0x08u
#define Indicator__PORT 6u
#define Indicator__PRT CYREG_PRT6_PRT
#define Indicator__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Indicator__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Indicator__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Indicator__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Indicator__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Indicator__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Indicator__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Indicator__PS CYREG_PRT6_PS
#define Indicator__SHIFT 3
#define Indicator__SLW CYREG_PRT6_SLW

/* ADC_DSM4 */
#define ADC_DSM4__BUF0 CYREG_DSM0_BUF0
#define ADC_DSM4__BUF1 CYREG_DSM0_BUF1
#define ADC_DSM4__BUF2 CYREG_DSM0_BUF2
#define ADC_DSM4__BUF3 CYREG_DSM0_BUF3
#define ADC_DSM4__CLK CYREG_DSM0_CLK
#define ADC_DSM4__CR0 CYREG_DSM0_CR0
#define ADC_DSM4__CR1 CYREG_DSM0_CR1
#define ADC_DSM4__CR10 CYREG_DSM0_CR10
#define ADC_DSM4__CR11 CYREG_DSM0_CR11
#define ADC_DSM4__CR12 CYREG_DSM0_CR12
#define ADC_DSM4__CR13 CYREG_DSM0_CR13
#define ADC_DSM4__CR14 CYREG_DSM0_CR14
#define ADC_DSM4__CR15 CYREG_DSM0_CR15
#define ADC_DSM4__CR16 CYREG_DSM0_CR16
#define ADC_DSM4__CR17 CYREG_DSM0_CR17
#define ADC_DSM4__CR2 CYREG_DSM0_CR2
#define ADC_DSM4__CR3 CYREG_DSM0_CR3
#define ADC_DSM4__CR4 CYREG_DSM0_CR4
#define ADC_DSM4__CR5 CYREG_DSM0_CR5
#define ADC_DSM4__CR6 CYREG_DSM0_CR6
#define ADC_DSM4__CR7 CYREG_DSM0_CR7
#define ADC_DSM4__CR8 CYREG_DSM0_CR8
#define ADC_DSM4__CR9 CYREG_DSM0_CR9
#define ADC_DSM4__DEM0 CYREG_DSM0_DEM0
#define ADC_DSM4__DEM1 CYREG_DSM0_DEM1
#define ADC_DSM4__MISC CYREG_DSM0_MISC
#define ADC_DSM4__OUT0 CYREG_DSM0_OUT0
#define ADC_DSM4__OUT1 CYREG_DSM0_OUT1
#define ADC_DSM4__REF0 CYREG_DSM0_REF0
#define ADC_DSM4__REF1 CYREG_DSM0_REF1
#define ADC_DSM4__REF2 CYREG_DSM0_REF2
#define ADC_DSM4__REF3 CYREG_DSM0_REF3
#define ADC_DSM4__RSVD1 CYREG_DSM0_RSVD1
#define ADC_DSM4__SW0 CYREG_DSM0_SW0
#define ADC_DSM4__SW2 CYREG_DSM0_SW2
#define ADC_DSM4__SW3 CYREG_DSM0_SW3
#define ADC_DSM4__SW4 CYREG_DSM0_SW4
#define ADC_DSM4__SW6 CYREG_DSM0_SW6
#define ADC_DSM4__TR0 CYREG_NPUMP_DSM_TR0
#define ADC_DSM4__TST0 CYREG_DSM0_TST0
#define ADC_DSM4__TST1 CYREG_DSM0_TST1

/* ADC_DEC */
#define ADC_DEC__COHER CYREG_DEC_COHER
#define ADC_DEC__CR CYREG_DEC_CR
#define ADC_DEC__DR1 CYREG_DEC_DR1
#define ADC_DEC__DR2 CYREG_DEC_DR2
#define ADC_DEC__DR2H CYREG_DEC_DR2H
#define ADC_DEC__GCOR CYREG_DEC_GCOR
#define ADC_DEC__GCORH CYREG_DEC_GCORH
#define ADC_DEC__GVAL CYREG_DEC_GVAL
#define ADC_DEC__OCOR CYREG_DEC_OCOR
#define ADC_DEC__OCORH CYREG_DEC_OCORH
#define ADC_DEC__OCORM CYREG_DEC_OCORM
#define ADC_DEC__OUTSAMP CYREG_DEC_OUTSAMP
#define ADC_DEC__OUTSAMPH CYREG_DEC_OUTSAMPH
#define ADC_DEC__OUTSAMPM CYREG_DEC_OUTSAMPM
#define ADC_DEC__OUTSAMPS CYREG_DEC_OUTSAMPS
#define ADC_DEC__PM_ACT_CFG CYREG_PM_ACT_CFG10
#define ADC_DEC__PM_ACT_MSK 0x01u
#define ADC_DEC__PM_STBY_CFG CYREG_PM_STBY_CFG10
#define ADC_DEC__PM_STBY_MSK 0x01u
#define ADC_DEC__SHIFT1 CYREG_DEC_SHIFT1
#define ADC_DEC__SHIFT2 CYREG_DEC_SHIFT2
#define ADC_DEC__SR CYREG_DEC_SR
#define ADC_DEC__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DEC_M1
#define ADC_DEC__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DEC_M2
#define ADC_DEC__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DEC_M3
#define ADC_DEC__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DEC_M4
#define ADC_DEC__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DEC_M5
#define ADC_DEC__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DEC_M6
#define ADC_DEC__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DEC_M7
#define ADC_DEC__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DEC_M8

/* ADC_IRQ */
#define ADC_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ADC_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ADC_IRQ__INTC_MASK 0x20000000u
#define ADC_IRQ__INTC_NUMBER 29u
#define ADC_IRQ__INTC_PRIOR_NUM 7u
#define ADC_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_29
#define ADC_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ADC_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Sample */
#define Sample__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define Sample__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define Sample__INTC_MASK 0x02u
#define Sample__INTC_NUMBER 1u
#define Sample__INTC_PRIOR_NUM 7u
#define Sample__INTC_PRIOR_REG CYREG_NVIC_PRI_1
#define Sample__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define Sample__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Toggle */
#define Toggle__0__MASK 0x02u
#define Toggle__0__PC CYREG_PRT6_PC1
#define Toggle__0__PORT 6u
#define Toggle__0__SHIFT 1
#define Toggle__AG CYREG_PRT6_AG
#define Toggle__AMUX CYREG_PRT6_AMUX
#define Toggle__BIE CYREG_PRT6_BIE
#define Toggle__BIT_MASK CYREG_PRT6_BIT_MASK
#define Toggle__BYP CYREG_PRT6_BYP
#define Toggle__CTL CYREG_PRT6_CTL
#define Toggle__DM0 CYREG_PRT6_DM0
#define Toggle__DM1 CYREG_PRT6_DM1
#define Toggle__DM2 CYREG_PRT6_DM2
#define Toggle__DR CYREG_PRT6_DR
#define Toggle__INP_DIS CYREG_PRT6_INP_DIS
#define Toggle__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Toggle__LCD_EN CYREG_PRT6_LCD_EN
#define Toggle__MASK 0x02u
#define Toggle__PORT 6u
#define Toggle__PRT CYREG_PRT6_PRT
#define Toggle__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Toggle__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Toggle__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Toggle__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Toggle__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Toggle__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Toggle__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Toggle__PS CYREG_PRT6_PS
#define Toggle__SHIFT 1
#define Toggle__SLW CYREG_PRT6_SLW

/* Clock */
#define Clock__CFG0 CYREG_CLKDIST_DCFG1_CFG0
#define Clock__CFG1 CYREG_CLKDIST_DCFG1_CFG1
#define Clock__CFG2 CYREG_CLKDIST_DCFG1_CFG2
#define Clock__CFG2_SRC_SEL_MASK 0x07u
#define Clock__INDEX 0x01u
#define Clock__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define Clock__PM_ACT_MSK 0x02u
#define Clock__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define Clock__PM_STBY_MSK 0x02u

/* Speed */
#define Speed__0__MASK 0x40u
#define Speed__0__PC CYREG_PRT1_PC6
#define Speed__0__PORT 1u
#define Speed__0__SHIFT 6
#define Speed__AG CYREG_PRT1_AG
#define Speed__AMUX CYREG_PRT1_AMUX
#define Speed__BIE CYREG_PRT1_BIE
#define Speed__BIT_MASK CYREG_PRT1_BIT_MASK
#define Speed__BYP CYREG_PRT1_BYP
#define Speed__CTL CYREG_PRT1_CTL
#define Speed__DM0 CYREG_PRT1_DM0
#define Speed__DM1 CYREG_PRT1_DM1
#define Speed__DM2 CYREG_PRT1_DM2
#define Speed__DR CYREG_PRT1_DR
#define Speed__INP_DIS CYREG_PRT1_INP_DIS
#define Speed__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Speed__LCD_EN CYREG_PRT1_LCD_EN
#define Speed__MASK 0x40u
#define Speed__PORT 1u
#define Speed__PRT CYREG_PRT1_PRT
#define Speed__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Speed__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Speed__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Speed__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Speed__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Speed__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Speed__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Speed__PS CYREG_PRT1_PS
#define Speed__SHIFT 6
#define Speed__SLW CYREG_PRT1_SLW

/* Mode */
#define Mode__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define Mode__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define Mode__INTC_MASK 0x01u
#define Mode__INTC_NUMBER 0u
#define Mode__INTC_PRIOR_NUM 7u
#define Mode__INTC_PRIOR_REG CYREG_NVIC_PRI_0
#define Mode__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define Mode__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Miscellaneous */
/* -- WARNING: define names containing LEOPARD or PANTHER are deprecated and will be removed in a future release */
#define CYDEV_DEBUGGING_DPS_SWD_SWV 6
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIG_FASTBOOT_ENABLED 1
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_MEMBER_5B 3u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_DIE_PSOC5LP 3u
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_DIE_PSOC5LP
#define BCLK__BUS_CLK__HZ 24000000U
#define BCLK__BUS_CLK__KHZ 24000U
#define BCLK__BUS_CLK__MHZ 24U
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x2E123069u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_5A 2u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5B
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5B_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REV_PSOC5LP_PRODUCTION
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_DMA 0
#define CYDEV_CONFIGURATION_ECC 1
#define CYDEV_CONFIGURATION_IMOENABLED CYDEV_CONFIG_FASTBOOT_ENABLED
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD_SWV
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_JTAG_4 1
#define CYDEV_DEBUGGING_DPS_JTAG_5 0
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_REQXRES 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_DEBUG_ENABLE_MASK 0x20u
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DEBUG
#define CYDEV_DMA_CHANNELS_AVAILABLE 24u
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 0x1000
#define CYDEV_INSTRUCT_CACHE_ENABLED 1
#define CYDEV_INTR_RISING 0x00000003u
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_PROTECTION_ENABLE 0
#define CYDEV_STACK_SIZE 0x4000
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5.0
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5.0
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5.0
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5.0
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5
#define CYDEV_VIO3_MV 5000
#define DMA_CHANNELS_USED__MASK0 0x00000000u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
