/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 5
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <Controller.h>
#include <Motor_aliases.h>
#include <Motor.h>
#include <PWM.h>
#include <ADC.h>
#include <Accelerator_aliases.h>
#include <Accelerator.h>
#include <Clock.h>
#include <Shifter_aliases.h>
#include <Shifter.h>
#include <ISR.h>
#include <Brake_aliases.h>
#include <Brake.h>
#include <Brakelight_aliases.h>
#include <Brakelight.h>
#include <Taillight_aliases.h>
#include <Taillight.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <ADC_theACLK.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_AMux.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
